In [1]:
import pandas as pd
import pyart

## You are using the Python ARM Radar Toolkit (Py-ART), an open source
## library for working with weather radar data. Py-ART is partly
## supported by the U.S. Department of Energy as part of the Atmospheric
## Radiation Measurement (ARM) Climate Research Facility, an Office of
## Science user facility.
##
## If you use this software to prepare a publication, please cite:
##
##     JJ Helmus and SM Collis, JORS 2016, doi: 10.5334/jors.119

In [2]:
radar = pyart.io.read('MDV-20150805-143535-PPIVol.nc')

In [3]:
radar.fields.keys()

dict_keys(['DBZH', 'DBZV', 'VELH', 'VELV'])

In [24]:
DBZH = radar.fields['DBZH']['data'][:]

In [25]:
DBZH

masked_array(
  data=[[6.0, 9.0, -12.5, ..., --, --, --],
        [6.0, 9.0, -13.0, ..., --, --, --],
        [7.5, 9.5, -12.5, ..., --, --, --],
        ...,
        [6.5, 7.5, -13.5, ..., --, --, --],
        [6.5, 6.0, -14.5, ..., --, --, --],
        [7.0, 7.0, -12.5, ..., --, --, --]],
  mask=[[False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        ...,
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],
  fill_value=-32768,
  dtype=float32)

In [26]:
pd.DataFrame(DBZH)

,0,1,2,3,4,5,6,7,8,9,...,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499
0,6.0,9.0,-12.5,-18.5,-17.0,-18.0,-17.0,-15.5,-14.5,-17.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6.0,9.0,-13.0,-18.5,-15.5,-15.5,-14.5,-13.5,-13.5,-14.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7.5,9.5,-12.5,-21.0,-22.0,-20.0,-18.0,-18.0,-16.5,-14.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.5,9.0,-15.0,-22.0,-23.0,-20.0,-18.0,-15.0,-13.0,-13.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6.5,10.5,-7.5,-20.5,-19.0,-19.5,-16.5,-15.0,-15.0,-16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9265,7.0,8.0,-13.0,-18.5,-20.0,-19.0,-16.5,-15.5,-15.5,-16.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9266,6.5,8.5,-14.0,-17.0,-20.0,-18.5,-17.5,-18.0,-16.5,-14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9267,6.5,7.5,-13.5,-19.5,-20.0,-18.0,-15.0,-13.5,-14.0,-14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9268,6.5,6.0,-14.5,-23.0,-20.0,-18.0,-16.5,-16.0,-15.5,-15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9269,7.0,7.0,-12.5,-21.0,-19.5,-19.0,-17.0,-15.0,-15.5,-17.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
radar.fields['DBZH']

{'long_name': 'equivalent_reflectivity_factor_h',
 'units': 'dBZ',
 '_FillValue': -32768,
 'coordinates': 'elevation azimuth range',
 'data': masked_array(
   data=[[6.0, 9.0, -12.5, ..., --, --, --],
         [6.0, 9.0, -13.0, ..., --, --, --],
         [7.5, 9.5, -12.5, ..., --, --, --],
         ...,
         [6.5, 7.5, -13.5, ..., --, --, --],
         [6.5, 6.0, -14.5, ..., --, --, --],
         [7.0, 7.0, -12.5, ..., --, --, --]],
   mask=[[False, False, False, ...,  True,  True,  True],
         [False, False, False, ...,  True,  True,  True],
         [False, False, False, ...,  True,  True,  True],
         ...,
         [False, False, False, ...,  True,  True,  True],
         [False, False, False, ...,  True,  True,  True],
         [False, False, False, ...,  True,  True,  True]],
   fill_value=-32768,
   dtype=float32)}

In [22]:
VELH = radar.fields['VELH']['data'][:]
VELH

masked_array(
  data=[[19.369998931884766, --, 21.770000457763672, ..., -11.25,
         -11.4399995803833, --],
        [20.850000381469727, --, -10.149999618530273, ..., 3.5,
         -10.699999809265137, --],
        [8.489999771118164, -7.929999828338623, --, ...,
         -9.779999732971191, --, --],
        ...,
        [-5.71999979019165, -6.639999866485596, -2.759999990463257, ...,
         10.149999618530273, 8.300000190734863, --],
        [-19.559999465942383, --, 11.4399995803833, ...,
         -4.059999942779541, -6.819999694824219, --],
        [-20.479999542236328, 10.149999618530273, 13.469999313354492,
         ..., --, -7.009999752044678, -13.649999618530273]],
  mask=[[False,  True, False, ..., False, False,  True],
        [False,  True, False, ..., False, False,  True],
        [False, False,  True, ..., False,  True,  True],
        ...,
        [False, False, False, ..., False, False,  True],
        [False,  True, False, ..., False, False,  True],
        [False, False, False, ...,  True, False, False]],
  fill_value=-32768,
  dtype=float32)

In [23]:
e2 = VELH[0,2490]
e2

-16.24

In [16]:
import numpy as np
print np.where(array1==0, 1, array1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
[val for val in DBZH if val == masked]

NameError: name 'masked' is not defined